() => {
 const g=game,D=g.debug,B=D.bits,rows=[];
 const normalize={STARTUP:'WINDUP',HIT_STUN:'STUNNED',GUARD:'GUARDING',DEFLECT:'DEFLECTING'};
 const state=p=>normalize[String(p.state).toUpperCase()]||String(p.state).toUpperCase();
 const check=(name,ok,actual)=>rows.push({name,passed:!!ok,actual});
 const reset=(a={},b={})=>{g.net=null;g.authority=null;g.mode='local';g.isHost=false;g.start('local');g.paused=true;g.silent=false;g.audio.setMuted(true);g.world.weather='dusk';Object.assign(g.world.players[0],{x:800,y:1080,vx:0,vy:0,ground:true,facing:1,loadout:['disc','flame']},a);Object.assign(g.world.players[1],{x:3000,y:1080,vx:0,vy:0,ground:true,facing:-1,loadout:['disc','flame']},b);return g.world.players;};
 const run=(a=0,b=0,n=1)=>D.step(a,b,n),near=(a,b)=>Math.abs(a-b)<.025;
 const until=(p,wanted,max=240)=>{for(let i=0;i<max&&state(p)!==wanted;i++)run();return state(p)===wanted;};
 check('Integrated build exposes the current runtime',/^\d+\.\d+\.\d+$/.test(D.version),{version:D.version,fsm:!!D.fsm,vitals:!!D.vitals});
 let p=reset();run(B.ATTACK);run(B.GUARD|B.DASH|B.TOOL1|B.ART);
 check('Windup rejects guard/dash/tool/art interruption',state(p[0])==='WINDUP'&&p[0].moveName==='light'&&!p[0].guard&&!p[0].dash&&p[0].spirit===20,{state:p[0].state,move:p[0].moveName,guard:p[0].guard,dash:p[0].dash,spirit:p[0].spirit});
 until(p[0],'ACTIVE');run(B.GUARD|B.DASH|B.ATTACK);check('Active frames reject guard/dash/new attack',state(p[0])==='ACTIVE'&&p[0].moveName==='light'&&!p[0].guard&&!p[0].dash,{state:p[0].state,move:p[0].moveName});
 until(p[0],'RECOVERY');run(B.GUARD|B.DASH|B.ATTACK);check('Unconfirmed recovery cannot cancel into guard/dash/attack',state(p[0])==='RECOVERY'&&p[0].moveName==='light'&&!p[0].guard&&!p[0].dash,{state:p[0].state,move:p[0].moveName});
 for(const test of [{hp:100,rate:35},{hp:75,rate:35},{hp:74.999,rate:15},{hp:50,rate:15},{hp:49.999,rate:0},{hp:1,rate:0}]){p=reset({hp:test.hp,posture:90,peace:12});run(0,0,60);const recovered=90-p[0].posture;check(`HP ${test.hp}: posture restores ${test.rate}/second`,near(recovered,test.rate),{hp:test.hp,recovered,expected:test.rate});}
 for(const test of [{hp:100,distance:350,expected:35},{hp:100,distance:351,expected:87.5},{hp:50,distance:351,expected:37.5},{hp:49.999,distance:351,expected:0}]){p=reset({hp:test.hp,posture:90,peace:12,state:'GUARD',guard:true,prevBits:B.GUARD},{x:800+test.distance});g.rawPrev=[B.GUARD,0];run(B.GUARD,0,60);const recovered=90-p[0].posture;check(`Guard regen HP${test.hp} distance${test.distance}`,near(recovered,test.expected),{recovered,expected:test.expected,state:p[0].state});}
 p=reset({hp:100,posture:90,peace:0});run(0,0,11);check('No recovery before peace frame 12',p[0].posture===90,{posture:p[0].posture,peace:p[0].peace});run();check('Recovery starts on peace frame 12',p[0].posture<90,{posture:p[0].posture,peace:p[0].peace});
 for(const test of [{aiControlled:true,phase:2,burn:0,expected:42},{aiControlled:false,phase:2,burn:0,expected:35},{aiControlled:true,phase:2,burn:44,frames:30,expected:5.25}]){p=reset({hp:100,posture:90,peace:12,...test});run(0,0,test.frames||60);const recovered=90-p[0].posture;check(`Phase2 recovery ai=${test.aiControlled} burn=${test.burn}`,near(recovered,test.expected),{recovered,expected:test.expected});}
 p=reset();const windows=[];for(let i=0;i<6;i++){run(B.GUARD);windows.push(p[0].deflectWindow);run(0,0,2);}check('Rapid empty deflect narrows 16→14→12 then stays usable',JSON.stringify(windows)==='[16,14,12,12,12,12]',windows);
 const DRINK=B.GOURD??B.DRINK??B.HEAL;check('Tonic has explicit action bit',Number.isInteger(DRINK),{DRINK});
 if(Number.isInteger(DRINK)){
  p=reset({hp:20});run(DRINK);run(0,0,52);check('Tonic does not heal before frame 54',p[0].hp===20,{hp:p[0].hp,state:p[0].state,st:p[0].st,tonics:p[0].tonics});run();check('Tonic heals forty HP at frame 54',p[0].hp===60&&p[0].tonics===2,{hp:p[0].hp,state:p[0].state,tonics:p[0].tonics});
  p=reset({hp:20});run(DRINK);run(0,0,20);D.hit(1,0,'light');const hpAtHit=p[0].hp;g.world.effects.hitstop=0;run(0,0,90);check('Interrupted tonic is consumed and never later heals',p[0].hp===hpAtHit&&p[0].tonics===2&&!p[0].healPending,{hp:p[0].hp,hpAtHit,tonics:p[0].tonics,healPending:p[0].healPending});
  p=reset({hp:80});run(DRINK);run(0,0,53);check('Tonic caps HP at 100',p[0].hp===100,{hp:p[0].hp});
 }
 p=reset({}, {x:880,hp:1});D.hit(0,1,'light');check('HP zero stuns without consuming a life node',p[1].hp===0&&p[1].nodes===2&&state(p[1])==='STUNNED'&&g.world.phase==='fighting',{hp:p[1].hp,nodes:p[1].nodes,state:p[1].state,phase:g.world.phase});
 g.world.effects.hitstop=0;g.execute(p[0],p[1]);check('First execution consumes one node and revives in phase two',p[1].nodes===1&&p[1].phase===2&&p[1].hp===100&&g.world.phase==='fighting'&&state(p[1])==='REVIVING',{nodes:p[1].nodes,phase:p[1].phase,hp:p[1].hp,state:p[1].state,roundPhase:g.world.phase,lockFrames:p[1].lockFrames});
 const lock=p[1].lockFrames;check('First revival has 90-frame lock',lock===90,{lock});g.world.effects.hitstop=0;run(0,0,89);check('Revival remains locked through 89 frames',state(p[1])==='REVIVING',{state:p[1].state,lockFrames:p[1].lockFrames});run();check('Revival releases both fighters at 90 frames with safe separation',state(p[1])!=='REVIVING'&&state(p[0])!=='EXECUTING'&&Math.abs(p[1].x-p[0].x)>150,{states:p.map(f=>f.state),x:p.map(f=>f.x)});
 Object.assign(p[0],{x:p[1].x-80,y:p[1].y,facing:1});Object.assign(p[1],{hp:0,posture:100,state:D.fsm?.STATE?.STUNNED||'STUNNED',stun:240,invuln:0});g.world.effects.hitstop=0;g.execute(p[0],p[1]);check('Second execution ends round and consumes final node',p[1].nodes===0&&g.world.phase==='ended'&&g.world.winner===0,{nodes:p[1].nodes,state:p[1].state,phase:g.world.phase,winner:g.world.winner});
 p=reset({x:1810,y:810},{x:3000});run(B.GRAPPLE);run(B.ATTACK);check('Grappling can legally cancel into an airborne slash',p[0].moveName==='air'&&state(p[0])==='WINDUP'&&p[0].grapple===null,{move:p[0].moveName,state:p[0].state,grapple:p[0].grapple});
 reset();const wa=JSON.parse(JSON.stringify(g.world)),wb=JSON.parse(JSON.stringify(g.world)),aAI=new RiftAI(),bAI=new RiftAI();for(const w of[wa,wb]){w.players[0].x=1050;w.players[1].x=1130;}Object.assign(wa.players[0],{state:'STARTUP',move:{...D.moves.thrust},moveName:'thrust',st:0});const aInputs=[],bInputs=[];let mutated=false;for(let i=1;i<=13;i++){wa.tick=wb.tick=i;const before=JSON.stringify([wa,wb]);aInputs.push(aAI.input(wa,wa.players[1],wa.players[0]));bInputs.push(bAI.input(wb,wb.players[1],wb.players[0]));if(before!==JSON.stringify([wa,wb]))mutated=true;}check('Production AI perceives threats only after twelve frames',JSON.stringify(aInputs.slice(0,12))===JSON.stringify(bInputs.slice(0,12))&&aAI.lastSight?.frame===1,{firstTwelve:aInputs.slice(0,12),control:bInputs.slice(0,12),perceivedFrame:aAI.lastSight?.frame,frame:aAI.frame});check('Production AI never mutates world state',!mutated,{mutated});
 reset();return rows;
}
